apiVersion: user.postgresql.crossplane.io/v1alpha1
kind: Mapping
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/mapping
  labels:
    testing.upbound.io/example-name: remote
  name: remote
spec:
  forProvider:
    options:
      password: pass
      user: admin
    serverName: ${postgresql_server.myserver_postgres.server_name}
    userName: ${postgresql_role.remote.name}

---

apiVersion: extension.postgresql.crossplane.io/v1alpha1
kind: Extension
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/mapping
  labels:
    testing.upbound.io/example-name: ext_postgres_fdw
  name: ext-postgres-fdw
spec:
  forProvider: {}

---

apiVersion: role.postgresql.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/mapping
  labels:
    testing.upbound.io/example-name: remote
  name: remote
spec:
  forProvider: {}
